before:
  hooks:
    - go mod download
builds:
  - id: "jd"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    dir: ./jd
    binary: jd
archives:
  - id: default
    builds:
      - jd
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
